import React from "react"
import Head from "next/head"
import Navbar from "../components/Navbar"

// Import all styles
import "../styles/Team.css"
import '../styles/Home.css'
import '../styles/Navbar.css'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <React.StrictMode>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
    </React.StrictMode>
  )
}

export default MyApp
